using System.ComponentModel;

namespace WallpaperSwitcher.Desktop
{
    partial class MainForm
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
                _toolTip.Dispose();
                _trayIcon.Dispose();
                _globalHotkeyManager.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code originally generated by Windows Form Designer and further generated/refined by AI

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            ComponentResourceManager resources = new ComponentResourceManager(typeof(MainForm));
            foldersManagementGroupBox = new GroupBox();
            removeFolderComboBox = new ComboBox();
            removeFolderButton = new Button();
            removeFolderLabel = new Label();
            addFolderLabel = new Label();
            addFolderButton = new Button();
            browseFolderButton = new Button();
            addFolderTextBox = new TextBox();
            currentFolderComboBox = new ComboBox();
            currentFolderLabel = new Label();
            nextWallpaperButton = new Button();
            modeComboBox = new ComboBox();
            settingsButton = new Button();
            mainPanel = new Panel();
            controlGroupBox = new GroupBox();
            foldersManagementGroupBox.SuspendLayout();
            mainPanel.SuspendLayout();
            controlGroupBox.SuspendLayout();
            SuspendLayout();
            // 
            // foldersManagementGroupBox
            // 
            foldersManagementGroupBox.Anchor = ((AnchorStyles)(((AnchorStyles.Top | AnchorStyles.Left)
                | AnchorStyles.Right)));
            foldersManagementGroupBox.Controls.Add(removeFolderComboBox);
            foldersManagementGroupBox.Controls.Add(removeFolderButton);
            foldersManagementGroupBox.Controls.Add(removeFolderLabel);
            foldersManagementGroupBox.Controls.Add(addFolderLabel);
            foldersManagementGroupBox.Controls.Add(addFolderButton);
            foldersManagementGroupBox.Controls.Add(browseFolderButton);
            foldersManagementGroupBox.Controls.Add(addFolderTextBox);
            foldersManagementGroupBox.Controls.Add(currentFolderComboBox);
            foldersManagementGroupBox.Controls.Add(currentFolderLabel);
            foldersManagementGroupBox.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold, GraphicsUnit.Point, ((byte)(0)));
            foldersManagementGroupBox.Location = new Point(15, 15);
            foldersManagementGroupBox.Name = "foldersManagementGroupBox";
            foldersManagementGroupBox.Size = new Size(565, 270);
            foldersManagementGroupBox.TabIndex = 0;
            foldersManagementGroupBox.TabStop = false;
            foldersManagementGroupBox.Text = "Folder Management";
            // 
            // removeFolderComboBox
            // 
            removeFolderComboBox.Anchor = ((AnchorStyles)(((AnchorStyles.Top | AnchorStyles.Left)
                | AnchorStyles.Right)));
            removeFolderComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            removeFolderComboBox.FormattingEnabled = true;
            removeFolderComboBox.Location = new Point(20, 220);
            removeFolderComboBox.Name = "removeFolderComboBox";
            removeFolderComboBox.Size = new Size(439, 23);
            removeFolderComboBox.TabIndex = 14;
            removeFolderComboBox.SelectedIndexChanged += removeFolderComboBox_SelectedIndexChanged;
            removeFolderComboBox.MouseEnter += removeFolderComboBox_MouseEnter;
            // 
            // removeFolderButton
            // 
            removeFolderButton.Anchor = ((AnchorStyles)((AnchorStyles.Top | AnchorStyles.Right)));
            removeFolderButton.BackColor = Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(215)))), ((int)(((byte)(218)))));
            removeFolderButton.Enabled = false;
            removeFolderButton.FlatAppearance.BorderSize = 0;
            removeFolderButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(174)))), ((int)(((byte)(182)))));
            removeFolderButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(154)))), ((int)(((byte)(162)))));
            removeFolderButton.FlatStyle = FlatStyle.Flat;
            removeFolderButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
            removeFolderButton.ForeColor = Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(28)))), ((int)(((byte)(36)))));
            removeFolderButton.Location = new Point(465, 219);
            removeFolderButton.Name = "removeFolderButton";
            removeFolderButton.Size = new Size(80, 25);
            removeFolderButton.TabIndex = 13;
            removeFolderButton.Text = "Remove";
            removeFolderButton.UseVisualStyleBackColor = false;
            removeFolderButton.Click += removeFolderButton_Click;
            removeFolderButton.EnabledChanged += Button_EnabledChanged;
            // 
            // removeFolderLabel
            // 
            removeFolderLabel.AutoSize = true;
            removeFolderLabel.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point, ((byte)(0)));
            removeFolderLabel.Location = new Point(17, 198);
            removeFolderLabel.Name = "removeFolderLabel";
            removeFolderLabel.Size = new Size(147, 15);
            removeFolderLabel.TabIndex = 12;
            removeFolderLabel.Text = "Select Folder to Remove:";
            // 
            // addFolderLabel
            // 
            addFolderLabel.AutoSize = true;
            addFolderLabel.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point, ((byte)(0)));
            addFolderLabel.Location = new Point(17, 118);
            addFolderLabel.Name = "addFolderLabel";
            addFolderLabel.Size = new Size(121, 15);
            addFolderLabel.TabIndex = 11;
            addFolderLabel.Text = "Add New Folder Path:";
            // 
            // addFolderButton
            // 
            addFolderButton.Anchor = ((AnchorStyles)((AnchorStyles.Top | AnchorStyles.Right)));
            addFolderButton.BackColor = Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(237)))), ((int)(((byte)(218)))));
            addFolderButton.Enabled = false;
            addFolderButton.FlatAppearance.BorderSize = 0;
            addFolderButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(222)))), ((int)(((byte)(188)))));
            addFolderButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(((int)(((byte)(164)))), ((int)(((byte)(215)))), ((int)(((byte)(179)))));
            addFolderButton.FlatStyle = FlatStyle.Flat;
            addFolderButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
            addFolderButton.ForeColor = Color.FromArgb(((int)(((byte)(21)))), ((int)(((byte)(87)))), ((int)(((byte)(36)))));
            addFolderButton.Location = new Point(465, 138);
            addFolderButton.Name = "addFolderButton";
            addFolderButton.Size = new Size(80, 25);
            addFolderButton.TabIndex = 10;
            addFolderButton.Text = "Add";
            addFolderButton.UseVisualStyleBackColor = false;
            addFolderButton.Click += addFolderButton_Click;
            addFolderButton.EnabledChanged += Button_EnabledChanged;
            // 
            // browseFolderButton
            // 
            browseFolderButton.Anchor = ((AnchorStyles)((AnchorStyles.Top | AnchorStyles.Right)));
            browseFolderButton.BackColor = Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(227)))), ((int)(((byte)(229)))));
            browseFolderButton.FlatAppearance.BorderSize = 0;
            browseFolderButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(206)))), ((int)(((byte)(208)))));
            browseFolderButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(((int)(((byte)(194)))), ((int)(((byte)(196)))), ((int)(((byte)(199)))));
            browseFolderButton.FlatStyle = FlatStyle.Flat;
            browseFolderButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
            browseFolderButton.ForeColor = Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(58)))), ((int)(((byte)(64)))));
            browseFolderButton.Location = new Point(379, 138);
            browseFolderButton.Name = "browseFolderButton";
            browseFolderButton.Size = new Size(80, 25);
            browseFolderButton.TabIndex = 9;
            browseFolderButton.Text = "Browse...";
            browseFolderButton.UseVisualStyleBackColor = false;
            browseFolderButton.Click += browseFolderButton_Click;
            browseFolderButton.EnabledChanged += Button_EnabledChanged;
            // 
            // addFolderTextBox
            // 
            addFolderTextBox.Anchor = ((AnchorStyles)(((AnchorStyles.Top | AnchorStyles.Left)
                | AnchorStyles.Right)));
            addFolderTextBox.BackColor = SystemColors.ControlLightLight;
            addFolderTextBox.BorderStyle = BorderStyle.FixedSingle;
            addFolderTextBox.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point, ((byte)(0)));
            addFolderTextBox.Location = new Point(20, 139);
            addFolderTextBox.Name = "addFolderTextBox";
            addFolderTextBox.ReadOnly = true;
            addFolderTextBox.Size = new Size(353, 23);
            addFolderTextBox.TabIndex = 5;
            addFolderTextBox.TextChanged += addFolderTextBox_TextChanged;
            // 
            // currentFolderComboBox
            // 
            currentFolderComboBox.Anchor = ((AnchorStyles)(((AnchorStyles.Top | AnchorStyles.Left)
                | AnchorStyles.Right)));
            currentFolderComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            currentFolderComboBox.FormattingEnabled = true;
            currentFolderComboBox.Location = new Point(20, 55);
            currentFolderComboBox.Name = "currentFolderComboBox";
            currentFolderComboBox.Size = new Size(525, 23);
            currentFolderComboBox.TabIndex = 1;
            currentFolderComboBox.SelectedIndexChanged += currentFolderComboBox_SelectedIndexChanged;
            currentFolderComboBox.MouseEnter += currentFolderComboBox_MouseEnter;
            // 
            // currentFolderLabel
            // 
            currentFolderLabel.AutoSize = true;
            currentFolderLabel.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point, ((byte)(0)));
            currentFolderLabel.Location = new Point(17, 33);
            currentFolderLabel.Name = "currentFolderLabel";
            currentFolderLabel.Size = new Size(144, 15);
            currentFolderLabel.TabIndex = 0;
            currentFolderLabel.Text = "Current Wallpaper Folder:";
            // 
            // nextWallpaperButton
            // 
            nextWallpaperButton.Anchor = ((AnchorStyles)((AnchorStyles.Top | AnchorStyles.Right)));
            nextWallpaperButton.BackColor = Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            nextWallpaperButton.Enabled = false;
            nextWallpaperButton.FlatAppearance.BorderSize = 0;
            nextWallpaperButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(204)))), ((int)(((byte)(255)))));
            nextWallpaperButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(197)))), ((int)(((byte)(245)))));
            nextWallpaperButton.FlatStyle = FlatStyle.Flat;
            nextWallpaperButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
            nextWallpaperButton.ForeColor = Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(69)))), ((int)(((byte)(149)))));
            nextWallpaperButton.Location = new Point(395, 30);
            nextWallpaperButton.Name = "nextWallpaperButton";
            nextWallpaperButton.Size = new Size(150, 45);
            nextWallpaperButton.TabIndex = 0;
            nextWallpaperButton.Text = "Next Wallpaper";
            nextWallpaperButton.UseVisualStyleBackColor = false;
            nextWallpaperButton.Click += nextWallpaperButton_Click;
            nextWallpaperButton.EnabledChanged += Button_EnabledChanged;
            // 
            // modeComboBox
            // 
            modeComboBox.Anchor = ((AnchorStyles)(((AnchorStyles.Top | AnchorStyles.Left)
                                                                             | AnchorStyles.Right)));
            modeComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            modeComboBox.FormattingEnabled = true;
            modeComboBox.Items.AddRange(new object[] {
                "Native Mode (System SlideShow)",
                "Custom Mode (Fast Switching)"});
            modeComboBox.Location = new Point(20, 40);
            modeComboBox.Name = "modeComboBox";
            modeComboBox.Size = new Size(353, 23);
            modeComboBox.TabIndex = 1;
            modeComboBox.SelectedIndexChanged += modeComboBox_SelectedIndexChanged;
            // 
            // settingsButton
            // 
            settingsButton.Anchor = ((AnchorStyles)(((AnchorStyles.Bottom | AnchorStyles.Left)
                                                                               | AnchorStyles.Right)));
            settingsButton.BackColor = Color.FromArgb(((int)(((byte)(209)))), ((int)(((byte)(236)))), ((int)(((byte)(241)))));
            settingsButton.FlatAppearance.BorderSize = 0;
            settingsButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(218)))), ((int)(((byte)(229)))));
            settingsButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(((int)(((byte)(156)))), ((int)(((byte)(207)))), ((int)(((byte)(219)))));
            settingsButton.FlatStyle = FlatStyle.Flat;
            settingsButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
            settingsButton.ForeColor = Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(84)))), ((int)(((byte)(96)))));
            settingsButton.Location = new Point(15, 415);
            settingsButton.Name = "settingsButton";
            settingsButton.Size = new Size(565, 30);
            settingsButton.TabIndex = 2;
            settingsButton.Text = "Settings";
            settingsButton.UseVisualStyleBackColor = false;
            settingsButton.Click += settingsButton_Click;
            settingsButton.EnabledChanged += Button_EnabledChanged;
            // 
            // mainPanel
            // 
            mainPanel.BackColor = Color.White;
            mainPanel.Controls.Add(controlGroupBox);
            mainPanel.Controls.Add(settingsButton);
            mainPanel.Controls.Add(foldersManagementGroupBox);
            mainPanel.Dock = DockStyle.Fill;
            mainPanel.Location = new Point(0, 0);
            mainPanel.Name = "mainPanel";
            mainPanel.Padding = new Padding(12);
            mainPanel.Size = new Size(594, 461);
            mainPanel.TabIndex = 3;
            // 
            // controlGroupBox
            // 
            controlGroupBox.Anchor = ((AnchorStyles)(((AnchorStyles.Top | AnchorStyles.Left)
                | AnchorStyles.Right)));
            controlGroupBox.Controls.Add(modeComboBox);
            controlGroupBox.Controls.Add(nextWallpaperButton);
            controlGroupBox.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
            controlGroupBox.Location = new Point(15, 300);
            controlGroupBox.Name = "controlGroupBox";
            controlGroupBox.Size = new Size(565, 100);
            controlGroupBox.TabIndex = 3;
            controlGroupBox.TabStop = false;
            controlGroupBox.Text = "Wallpaper Control";
            // 
            // MainForm
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(594, 461);
            Controls.Add(mainPanel);
            Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point, ((byte)(0)));
            FormBorderStyle = FormBorderStyle.FixedSingle;
            Icon = (Icon)resources.GetObject("$this.Icon");
            MaximizeBox = false;
            Name = "MainForm";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Wallpaper Switcher";
            FormClosing += new FormClosingEventHandler(MainForm_FormClosing);
            Load += MainForm_Load;
            foldersManagementGroupBox.ResumeLayout(false);
            foldersManagementGroupBox.PerformLayout();
            mainPanel.ResumeLayout(false);
            controlGroupBox.ResumeLayout(false);
            ResumeLayout(false);
        }

        #endregion

        private void Button_EnabledChanged(object sender, System.EventArgs e)
        {
            if (sender is Button button)
            {
                if (button.Enabled)
                {
                    // Restore original colors when enabled
                    if (button.Tag is Color[] colors)
                    {
                        button.BackColor = colors[0];
                        button.ForeColor = colors[1];
                    }
                }
                else
                {
                    // Store original colors and apply disabled style
                    button.Tag = new Color[] { button.BackColor, button.ForeColor };
                    button.BackColor = Color.FromArgb(242, 242, 242);
                    button.ForeColor = Color.Gray;
                }
            }
        }

        private GroupBox foldersManagementGroupBox;
        private ComboBox currentFolderComboBox;
        private Label currentFolderLabel;
        private Button browseFolderButton;
        private Button nextWallpaperButton;
        private Button addFolderButton;
        private Label addFolderLabel;
        private Label removeFolderLabel;
        private ComboBox removeFolderComboBox;
        private Button removeFolderButton;
        private TextBox addFolderTextBox;
        private ComboBox modeComboBox;
        private Button settingsButton;
        private Panel mainPanel;
        private GroupBox controlGroupBox;
    }
}