
namespace WallpaperSwitcher.Desktop
{
    partial class SettingsForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code originally generated by Windows Form Designer and further generated/refined by AI

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SettingsForm));
            nextWallpaperHkLabel = new Label();
            nextWallpaperHkTextBox = new TextBox();
            nextWallpaperHkModifyButton = new Button();
            nextWallpaperHkSaveButton = new Button();
            folderHkComboBox = new ComboBox();
            folderHkTextBox = new TextBox();
            folderHkModifyButton = new Button();
            folderHkSaveButton = new Button();
            folderHkLabel = new Label();
            launchStartupCheckBox = new CheckBox();
            settingsFormOkButton = new Button();
            hotkeysGroupBox = new GroupBox();
            generalGroupBox = new GroupBox();
            mainPanel = new Panel();
            hotkeysGroupBox.SuspendLayout();
            generalGroupBox.SuspendLayout();
            mainPanel.SuspendLayout();
            SuspendLayout();
            // 
            // nextWallpaperHkLabel
            // 
            nextWallpaperHkLabel.AutoSize = true;
            nextWallpaperHkLabel.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point, ((byte)(0)));
            nextWallpaperHkLabel.Location = new Point(20, 35);
            nextWallpaperHkLabel.Name = "nextWallpaperHkLabel";
            nextWallpaperHkLabel.Size = new Size(142, 15);
            nextWallpaperHkLabel.TabIndex = 0;
            nextWallpaperHkLabel.Text = "Next Wallpaper Hotkey:";
            // 
            // nextWallpaperHkTextBox
            // 
            nextWallpaperHkTextBox.Anchor = ((AnchorStyles)(((AnchorStyles.Top | AnchorStyles.Left)
           | AnchorStyles.Right)));
            nextWallpaperHkTextBox.BackColor = SystemColors.ControlLightLight;
            nextWallpaperHkTextBox.BorderStyle = BorderStyle.FixedSingle;
            nextWallpaperHkTextBox.Location = new Point(168, 32);
            nextWallpaperHkTextBox.Name = "nextWallpaperHkTextBox";
            nextWallpaperHkTextBox.ReadOnly = true;
            nextWallpaperHkTextBox.Size = new Size(200, 23);
            nextWallpaperHkTextBox.TabIndex = 1;
            // 
            // nextWallpaperHkModifyButton
            // 
            nextWallpaperHkModifyButton.Anchor = ((AnchorStyles)((AnchorStyles.Top | AnchorStyles.Right)));
            nextWallpaperHkModifyButton.BackColor = Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(227)))), ((int)(((byte)(229)))));
            nextWallpaperHkModifyButton.FlatAppearance.BorderSize = 0;
            nextWallpaperHkModifyButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(206)))), ((int)(((byte)(208)))));
            nextWallpaperHkModifyButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(((int)(((byte)(194)))), ((int)(((byte)(196)))), ((int)(((byte)(199)))));
            nextWallpaperHkModifyButton.FlatStyle = FlatStyle.Flat;
            nextWallpaperHkModifyButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
            nextWallpaperHkModifyButton.ForeColor = Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(58)))), ((int)(((byte)(64)))));
            nextWallpaperHkModifyButton.Location = new Point(384, 31);
            nextWallpaperHkModifyButton.Name = "nextWallpaperHkModifyButton";
            nextWallpaperHkModifyButton.Size = new Size(75, 25);
            nextWallpaperHkModifyButton.TabIndex = 2;
            nextWallpaperHkModifyButton.Text = "Modify";
            nextWallpaperHkModifyButton.UseVisualStyleBackColor = false;
            nextWallpaperHkModifyButton.Click += nextWallpaperHkModifyButton_Click;
            // 
            // nextWallpaperHkSaveButton
            // 
            nextWallpaperHkSaveButton.Anchor = ((AnchorStyles)((AnchorStyles.Top | AnchorStyles.Right)));
            nextWallpaperHkSaveButton.BackColor = Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(237)))), ((int)(((byte)(218)))));
            nextWallpaperHkSaveButton.Enabled = false;
            nextWallpaperHkSaveButton.FlatAppearance.BorderSize = 0;
            nextWallpaperHkSaveButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(222)))), ((int)(((byte)(188)))));
            nextWallpaperHkSaveButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(((int)(((byte)(164)))), ((int)(((byte)(215)))), ((int)(((byte)(179)))));
            nextWallpaperHkSaveButton.FlatStyle = FlatStyle.Flat;
            nextWallpaperHkSaveButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
            nextWallpaperHkSaveButton.ForeColor = Color.FromArgb(((int)(((byte)(21)))), ((int)(((byte)(87)))), ((int)(((byte)(36)))));
            nextWallpaperHkSaveButton.Location = new Point(465, 31);
            nextWallpaperHkSaveButton.Name = "nextWallpaperHkSaveButton";
            nextWallpaperHkSaveButton.Size = new Size(75, 25);
            nextWallpaperHkSaveButton.TabIndex = 3;
            nextWallpaperHkSaveButton.Text = "Save";
            nextWallpaperHkSaveButton.UseVisualStyleBackColor = false;
            nextWallpaperHkSaveButton.Click += nextWallpaperHkSaveButton_Click;
            // 
            // folderHkComboBox
            // 
            folderHkComboBox.Anchor = ((AnchorStyles)(((AnchorStyles.Top | AnchorStyles.Left)
           | AnchorStyles.Right)));
            folderHkComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            folderHkComboBox.FormattingEnabled = true;
            folderHkComboBox.Location = new Point(168, 70);
            folderHkComboBox.Name = "folderHkComboBox";
            folderHkComboBox.Size = new Size(372, 23);
            folderHkComboBox.TabIndex = 4;
            folderHkComboBox.SelectedIndexChanged += folderHkComboBox_SelectedIndexChanged;
            // 
            // folderHkTextBox
            // 
            folderHkTextBox.Anchor = ((AnchorStyles)(((AnchorStyles.Top | AnchorStyles.Left)
           | AnchorStyles.Right)));
            folderHkTextBox.BackColor = SystemColors.ControlLightLight;
            folderHkTextBox.BorderStyle = BorderStyle.FixedSingle;
            folderHkTextBox.Location = new Point(168, 108);
            folderHkTextBox.Name = "folderHkTextBox";
            folderHkTextBox.ReadOnly = true;
            folderHkTextBox.Size = new Size(200, 23);
            folderHkTextBox.TabIndex = 5;
            // 
            // folderHkModifyButton
            // 
            folderHkModifyButton.Anchor = ((AnchorStyles)((AnchorStyles.Top | AnchorStyles.Right)));
            folderHkModifyButton.BackColor = Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(227)))), ((int)(((byte)(229)))));
            folderHkModifyButton.Enabled = false;
            folderHkModifyButton.FlatAppearance.BorderSize = 0;
            folderHkModifyButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(206)))), ((int)(((byte)(208)))));
            folderHkModifyButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(((int)(((byte)(194)))), ((int)(((byte)(196)))), ((int)(((byte)(199)))));
            folderHkModifyButton.FlatStyle = FlatStyle.Flat;
            folderHkModifyButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
            folderHkModifyButton.ForeColor = Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(58)))), ((int)(((byte)(64)))));
            folderHkModifyButton.Location = new Point(384, 107);
            folderHkModifyButton.Name = "folderHkModifyButton";
            folderHkModifyButton.Size = new Size(75, 25);
            folderHkModifyButton.TabIndex = 6;
            folderHkModifyButton.Text = "Modify";
            folderHkModifyButton.UseVisualStyleBackColor = false;
            folderHkModifyButton.Click += folderHkModifyButton_Click;
            // 
            // folderHkSaveButton
            // 
            folderHkSaveButton.Anchor = ((AnchorStyles)((AnchorStyles.Top | AnchorStyles.Right)));
            folderHkSaveButton.BackColor = Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(237)))), ((int)(((byte)(218)))));
            folderHkSaveButton.Enabled = false;
            folderHkSaveButton.FlatAppearance.BorderSize = 0;
            folderHkSaveButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(222)))), ((int)(((byte)(188)))));
            folderHkSaveButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(((int)(((byte)(164)))), ((int)(((byte)(215)))), ((int)(((byte)(179)))));
            folderHkSaveButton.FlatStyle = FlatStyle.Flat;
            folderHkSaveButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
            folderHkSaveButton.ForeColor = Color.FromArgb(((int)(((byte)(21)))), ((int)(((byte)(87)))), ((int)(((byte)(36)))));
            folderHkSaveButton.Location = new Point(465, 107);
            folderHkSaveButton.Name = "folderHkSaveButton";
            folderHkSaveButton.Size = new Size(75, 25);
            folderHkSaveButton.TabIndex = 7;
            folderHkSaveButton.Text = "Save";
            folderHkSaveButton.UseVisualStyleBackColor = false;
            folderHkSaveButton.Click += folderHkSaveButton_Click;
            // 
            // folderHkLabel
            // 
            folderHkLabel.AutoSize = true;
            folderHkLabel.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point, ((byte)(0)));
            folderHkLabel.Location = new Point(20, 73);
            folderHkLabel.Name = "folderHkLabel";
            folderHkLabel.Size = new Size(124, 15);
            folderHkLabel.TabIndex = 8;
            folderHkLabel.Text = "Folder Hotkey:";
            // 
            // launchStartupCheckBox
            // 
            launchStartupCheckBox.AutoSize = true;
            launchStartupCheckBox.Location = new Point(23, 30);
            launchStartupCheckBox.Name = "launchStartupCheckBox";
            launchStartupCheckBox.Size = new Size(122, 19);
            launchStartupCheckBox.TabIndex = 12;
            launchStartupCheckBox.Text = "Launch at startup";
            launchStartupCheckBox.UseVisualStyleBackColor = true;
            launchStartupCheckBox.CheckedChanged += launchStartupCheckBox_CheckedChanged;
            // 
            // settingsFormOkButton
            // 
            settingsFormOkButton.Anchor = ((AnchorStyles)((AnchorStyles.Bottom | AnchorStyles.Right)));
            settingsFormOkButton.BackColor = Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            settingsFormOkButton.DialogResult = DialogResult.OK;
            settingsFormOkButton.FlatAppearance.BorderSize = 0;
            settingsFormOkButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(204)))), ((int)(((byte)(255)))));
            settingsFormOkButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(197)))), ((int)(((byte)(245)))));
            settingsFormOkButton.FlatStyle = FlatStyle.Flat;
            settingsFormOkButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
            settingsFormOkButton.ForeColor = Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(69)))), ((int)(((byte)(149)))));
            settingsFormOkButton.Location = new Point(490, 275);
            settingsFormOkButton.Name = "settingsFormOkButton";
            settingsFormOkButton.Size = new Size(90, 30);
            settingsFormOkButton.TabIndex = 13;
            settingsFormOkButton.Text = "OK";
            settingsFormOkButton.UseVisualStyleBackColor = false;
            settingsFormOkButton.Click += settingsFormOkButton_Click;
            // 
            // hotkeysGroupBox
            // 
            hotkeysGroupBox.Anchor = ((AnchorStyles)(((AnchorStyles.Top | AnchorStyles.Left)
           | AnchorStyles.Right)));
            hotkeysGroupBox.Controls.Add(nextWallpaperHkLabel);
            hotkeysGroupBox.Controls.Add(nextWallpaperHkTextBox);
            hotkeysGroupBox.Controls.Add(nextWallpaperHkModifyButton);
            hotkeysGroupBox.Controls.Add(nextWallpaperHkSaveButton);
            hotkeysGroupBox.Controls.Add(folderHkComboBox);
            hotkeysGroupBox.Controls.Add(folderHkLabel);
            hotkeysGroupBox.Controls.Add(folderHkTextBox);
            hotkeysGroupBox.Controls.Add(folderHkSaveButton);
            hotkeysGroupBox.Controls.Add(folderHkModifyButton);
            hotkeysGroupBox.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold, GraphicsUnit.Point, ((byte)(0)));
            hotkeysGroupBox.Location = new Point(15, 15);
            hotkeysGroupBox.Name = "hotkeysGroupBox";
            hotkeysGroupBox.Size = new Size(565, 150);
            hotkeysGroupBox.TabIndex = 14;
            hotkeysGroupBox.TabStop = false;
            hotkeysGroupBox.Text = "Hotkeys";
            // 
            // generalGroupBox
            // 
            generalGroupBox.Anchor = ((AnchorStyles)(((AnchorStyles.Top | AnchorStyles.Left)
           | AnchorStyles.Right)));
            generalGroupBox.Controls.Add(launchStartupCheckBox);
            generalGroupBox.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold, GraphicsUnit.Point, ((byte)(0)));
            generalGroupBox.Location = new Point(15, 180);
            generalGroupBox.Name = "generalGroupBox";
            generalGroupBox.Size = new Size(565, 75);
            generalGroupBox.TabIndex = 15;
            generalGroupBox.TabStop = false;
            generalGroupBox.Text = "General";
            // 
            // mainPanel
            // 
            mainPanel.BackColor = Color.White;
            mainPanel.Controls.Add(hotkeysGroupBox);
            mainPanel.Controls.Add(settingsFormOkButton);
            mainPanel.Controls.Add(generalGroupBox);
            mainPanel.Dock = DockStyle.Fill;
            mainPanel.Location = new Point(0, 0);
            mainPanel.Name = "mainPanel";
            mainPanel.Padding = new Padding(12);
            mainPanel.Size = new Size(594, 321);
            mainPanel.TabIndex = 16;
            // 
            // SettingsForm
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(594, 321);
            Controls.Add(mainPanel);
            Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point, ((byte)(0)));
            FormBorderStyle = FormBorderStyle.FixedDialog;
            Icon = (Icon)resources.GetObject("$this.Icon");
            MaximizeBox = false;
            MinimizeBox = false;
            Name = "SettingsForm";
            ShowInTaskbar = false;
            StartPosition = FormStartPosition.CenterParent;
            Text = "Wallpaper Switcher Settings";
            Load += SettingsForm_Load;
            hotkeysGroupBox.ResumeLayout(false);
            hotkeysGroupBox.PerformLayout();
            generalGroupBox.ResumeLayout(false);
            generalGroupBox.PerformLayout();
            mainPanel.ResumeLayout(false);
            ResumeLayout(false);

        }

        #endregion

        private Label nextWallpaperHkLabel;
        private TextBox nextWallpaperHkTextBox;
        private Button nextWallpaperHkModifyButton;
        private Button nextWallpaperHkSaveButton;
        private ComboBox folderHkComboBox;
        private TextBox folderHkTextBox;
        private Button folderHkModifyButton;
        private Button folderHkSaveButton;
        private Label folderHkLabel;
        private CheckBox launchStartupCheckBox;
        private Button settingsFormOkButton;
        private GroupBox hotkeysGroupBox;
        private GroupBox generalGroupBox;
        private Panel mainPanel;
    }
}